language: r
sudo: required
cache: packages

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

git:
 depth: 3 

r_packages:
 - devtools
 - checkpoint
 - rmarkdown

r_github_packages:
 - MangoTheCat/visualTest
 - ukgovdatascience/eesectors

install:
  - R -e "0" --args --bootstrap-packrat

before_script:
  - chmod +x ./_build.R
  - chmod +x ./_deploy.sh

script:
  - Rscript ./_build.R
  - ./_deploy.sh
