# Key Findings {#key_findings}

## GVA {#key_findings_gva}

* In 2015 the contribution of DCMS sectors to the UK economy (GVA) was £221bn, or 13.3 per cent of UK GVA.

* The GVA of DCMS sectors has grown at a faster rate than the economy as a whole, increasing by 3.6 per cent since 2014 (£213bn), and 24.8 per cent since 2010 (£177bn),compared with increases of 2.3 per cent and 17.4 per cent for the whole UK economy.

* The Cultural Sector had the greatest percentage increase between 2014 and 2015 (15.0%), whilst Sport had the greatest percentage increase since 2010 (44.4%).

## Exports and Imports
* In 2014, DCMS sectors exported £37.7bn worth of services to the rest of the world, 17.2 per cent of total UK service exports. 
This was 13.7 per cent higher than 2013, and 40.5 per cent higher than 2010, a much faster rate than growth than was seen for UK exports of services as a whole (which were 2.0% and 25.6% respectively).

* In 2014, 42.3 per cent of exports of services from DCMS sectors went to countries in the European Union (EU): this compares to 38.6 per cent of all UK exports of services. 

* In 2014, DCMS sectors imported £19.4bn worth of services from the rest of the world, 14.6 per cent of total UK imports of services. 
This was a 9.0 per cent increase from 2013, compared with a 0.5 per cent decrease for the UK as a whole.

* In 2014, 53.7 per cent of imports of services for DCMS sectors came from countries in the European Union (EU), this compares to 47.8 per cent of total UK service imports.

## Number of enterprises
* In 2014, DCMS sectors accounted for 15.8 per cent of all UK enterprises, approximately 331 thousand enterprises. 
The number of enterprises in all DCMS sectors has increased by 4.1 per cent between 2013 and 2014, and by 19.5 per cent since 2008.

* The Digital Sector had the largest growth in number of enterprises, increasing by 5.7 per
cent between 2013 and 2014. A number of sectors had a reduction in the number of
enterprises. The Gambling sector had the largest decrease since 2008 (29.1%). 
Tourism had the largest decrease since 2013 (11.4%)
