# GVA {#gva}

This chapter presents UK GVA estimates for each DCMS sector at a headline level. 
All estimates of GVA are shown in current prices (i.e. not adjusted for inflation). 
GVA estimates are consistent with the Office for National Statistics National Accounts. 
Where data are not available directly from the Supply and Use tables the Annual Business Survey (ABS) has been used to allocate GVA within the categories available in the Supply and Use tables.
Further information on the methodology is available in the associated [methodology note]().

## Summary
It is estimated that in 2015 the contribution of DCMS sectors to the UK economy (GVA) was £221bn[^1], or 13.3 per cent of UK GVA.
The GVA of DCMS sectors has grown at a faster rate than the economy as a whole, increasing by 3.6 per cent since 2014 (£213bn), and 24.8 per cent since 2010 (£177bn). 
This compares to increases of 2.3 per cent and 17.4 per cent respectively for the UK economy as a whole.

[^1]: Data are in current prices (i.e. have not been adjusted for inflation).

```{r GVA_table, warning=FALSE, message=FALSE, results='asis'}

library(EESectors)
GVA_table(GVA, html = TRUE)

```

The Cultural Sector had the greatest percentage increase between 2014 and 2015 (15.0%), whilst Sport had the greatest percentage increase since 2010 (44.4%), despite a small decrease between 2014 and 2015 (of 1.5%). 
Creative Industries had the second greatest increase over the past five years (34.0%). 
Figures 3.2 and 3.3 show the growth rate for DCMS sectors as a whole and for each DCMS sector.

The Digital Sector alone made up half of the DCMS sectors’ GVA in 2015 (7.1% of UK GVA), whilst Creative Industries represented over a third (5.3% of UK GVA).
There is considerable overlap between the DCMS sectors for example 3.8 per cent of UK GVA is in both Creative Industries and the Digital Sector.
The overlap between sectors is represented in Figure 3.4 below, and means that the individual sectors cannot be summed to get an estimate of the GVA for all DCMS sectors combined.
