---
title: "Reproducible Analytical Pipelines Demo"
date: "28 November 2016"
output:
  html_document: default
  word_document: default
---

## THIS IS A PROTOTYPE BASED ON AN EXISTING PUBLICATION IN THE PUBLIC DOMAIN

# Department for X and Y {-}
**Date**: August 2016  
**Contact**: <someone@xandy.gov.uk>

```{r setup, echo=FALSE, include=FALSE, error=FALSE, echo=FALSE}

# Note that this .Renviron should be run prior to compilation.

knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE,
  echo = FALSE,
  cache = FALSE
  )


library(dplyr)
library(knitr)

# May need to install this first:

devtools::install_github('ukgovdatascience/eesectors')

library(eesectors)
```

```{r introduction, child='01-introduction.Rmd'}
```

```{r key_findings, child='02-key-findings.Rmd'}
```

```{r GVA, child='03-GVA.Rmd'}
```

```{r exports-imports, child='04-exports-imports.Rmd'}
```

```{r enterprises, child='05-enterprises.Rmd'}
```

```{r summary, child='06-summary.Rmd'}
```

```{r annexA, child='07-annexA.Rmd'}
```

```{r save_repro_log}

write(.libPaths(), file = '.libpaths')
capture.output(sessionInfo(), file = '.sessioninfo')

```
